openapi: 3.0.3
info:
  title: KinConnect
  description: For kin to connect
  version: 1.0.2
servers:
  - url: https://api.kinconnect.com

paths:
  /auth/register:
    post:
      summary: 用户注册
      description: 注册一个新用户账号（需进行邮箱验证）
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: han@example.com
                password:
                  type: string
                  format: password
                  example: myStrongPassword123
      responses:
        '201':
          description: 注册成功，验证邮件已发送
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    example: 64f21a9b3e
                  message:
                    type: string
                    example: 注册成功，请查收验证邮件
        '400':
          description: 请求参数错误
        '409':
          description: 邮箱已被注册

  /auth/verify-email:
    post:
      summary: 邮箱验证
      description: 用户通过邮件中的验证码完成邮箱验证
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - code
              properties:
                email:
                  type: string
                  format: email
                  example: han@example.com
                code:
                  type: string
                  description: 邮箱验证码
                  example: 123456
      responses:
        '200':
          description: 邮箱验证成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 邮箱验证成功
        '400':
          description: 验证码错误或已过期
        '404':
          description: 邮箱未找到

  /auth/login:
    post:
      summary: 用户登录（邮箱）
      description: 使用邮箱和密码登录，需先完成邮箱验证
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: han@example.com
                password:
                  type: string
                  format: password
                  example: myStrongPassword123
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT 令牌
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  expiresIn:
                    type: integer
                    description: Token 有效期（秒）
                    example: 3600
        '401':
          description: 邮箱或密码错误
        '403':
          description: 邮箱未验证
        '404':
          description: 邮箱未注册
